export const TABLAS = {
    MARCA: 'marcas',
    PAIS: 'paises',
    PROVEEDORES: 'proveedores',
    CAJAS: 'cajas',
    COMESTIBLES: "comestibles",
    DESECHABLES: "desechables",
    MESAS: "mesas",
    BEBIDA_CALIENTE: "bebidasCalientes",
    BEBIDA_GASEOSA: "bebidasGaseosas",
    BEBIDA_HELADA: "bebidasHeladas",
    BITACORA: "bitacoras",
    BUFFET: "buffet",
    CLIENTE: "clientes",
    CONSECUTIVO: "consecutivos",
    EMPLEADO: "empleados",
    ESPECIAL: "especiales",
    FACTURA: "facturas",
    LICOR: "licores",
    LIMPIEZA: "limpieza",
    PERSONAL: "personal",
    PUESTO: "puestos",
    RESTAURANTE: "restaurantes",
    ROL: "roles",
    TECNOLOGIA: "tecnologia",
    UNIDAD_DE_MEDIDA: "medidas",
    UTENSILIO: "utensilios",
    VINO: "vinos",
    USUARIO: "usuarios",
};

export const ROLES = {
    ADMIN: "Administrador",
    SEGURIDAD: "Seguridad",
    RESTAURANTE: "Restaurante",
    CONTABILIDAD: "Contabilidad"
};